server:
 port: 9090

security:
 basic:
  enabled: false

authentication:
 xauth:
  secret: myXAuthSecret
  # Token is valid 30 minutes
  tokenValidityInSeconds: 1800

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./theDatabase
    username: mbe
    password: test


